log:
  level: debug

enable:
  - file
module:
  file:
    root: /Users/glen/work/tmp/test_tora
    allowPut: true
    allowListDir: true
    allowDelete: true

auth:
  token:
    testtoken:
      allow: true
      modules: ["file"]
